version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - govet
    - gosec
    - ineffassign
    - unused

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

run:
  timeout: 5m
